-- Migration number: 0001 	 2024-05-24T00:00:00.000Z
CREATE TABLE IF NOT EXISTS pendaftaran_santri (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nama_depan TEXT,
    nama_belakang TEXT,
    nik TEXT,
    no_kk TEXT,
    nisn TEXT,
    jenis_kelamin TEXT,
    tempat_lahir TEXT,
    tanggal_lahir TEXT,
    agama TEXT,
    agama_lainnya TEXT,
    pendidikan_terakhir TEXT,
    jenjang_kelas TEXT,
    hobi TEXT,
    cita_cita TEXT,
    nama_ayah_depan TEXT,
    nama_ayah_belakang TEXT,
    nik_ayah TEXT,
    no_hp_ayah TEXT,
    pendidikan_ayah TEXT,
    pendidikan_ayah_lainnya TEXT,
    pekerjaan_ayah TEXT,
    pekerjaan_ayah_lainnya TEXT,
    penghasilan_ayah TEXT,
    nama_ibu_depan TEXT,
    nama_ibu_belakang TEXT,
    nik_ibu TEXT,
    no_hp_ibu TEXT,
    pendidikan_ibu TEXT,
    pendidikan_ibu_lainnya TEXT,
    pekerjaan_ibu TEXT,
    pekerjaan_ibu_lainnya TEXT,
    penghasilan_ibu TEXT,
    alamat_jalan TEXT,
    alamat_kecamatan TEXT,
    alamat_kota TEXT,
    alamat_provinsi TEXT,
    alamat_kode_pos TEXT,
    alamat_negara TEXT,
    foto_santri TEXT,
    scan_kk TEXT,
    scan_ijazah TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
